### ISSUE TITLE
`drs` function seems stuck when `n` is too high

### ISSUE THREAD

**Issue by BottCode** [dgdguk/drs#1]
Hi,
I'm using `drs` function and sometimes it freezes.

This is the code I'm testing:

```python
from drs import drs

n = 30
maxU = 1.6

drs (n, maxU, [0.6 for _ in range(n)], [0.05 for _ in range(n)])
print("drs completed")
```

When:

-  `n = 30`, it works.
- `n = 32` the execution freezes and the following warning is prompted: `/usr/local/lib/python3.8/dist-packages/numpy/linalg/linalg.py:2159: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)`
- `n > 33` no warnings are prompted and the execution freezes.

I'm working on Ubuntu and Python 3.8.5.

Do you observe the same behaviour?

**Comment by dgdguk** [comment]
This isn't quite expected behaviour - DRS should be throwing an error for both the n = 32 and n > 33 cases. Given that 0.05 * 32 = 1.6, setting the lower bound to 0.05 for n=32 has one solution (0.05 for all values) and is probably user error, and for n >= 33 there are no solutions. If you set maxU higher or the lower bounds lower, so that solutions are possible for higher values of n, it should work.

The error not triggering is a bug though, so thanks for brigging this to my attention. I'll investigate what's causing this.

**Comment by BottCode** [comment]
Thanks for your answer, keep me updated on your investigation.
